### PR TITLE
Read Queue ARN from Environment Variable

### PR DESCRIPTION
**Pull request by pgonzalez-otf**
*Issue #84 , if available:*

*Description of changes: Added file being transcoded to result message. 
Added file name (less extension) as folder for video output.
Read transcode queue from lambda environment variable.*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by axptwig** [comment]
One additional thing that needs to be done is that the queueArn environment variable needs to be defined in the Vod Cloudformation template located in `./provider-utils/awscloudformation/cloudformation-templates/inputTriggerLambda.template`

This env var needs to be set the the queue arn which needs to be looked up by amplify video and set in the cloudformation.

**Comment by pgonzalez-otf** [comment]
@axptwig,
What should I use as a reference for the queue ARN?
I have this:
`QUEUE_ARN: !Ref `
in the .template file

**Comment by axptwig** [comment]
Fairly certain you need to make a function in `/provider-utils/awscloudformation/service-walkthroughs/vod-push.js` @wizage will have more info on where to put this code

**Comment by wizage** [comment]
So after thinking this over more, I think this is a valuable add with the caveat of if you need to share this across multiple accounts this can break. So I think the current logic should be left in there to get a queue if there is no queue provided. I.E.

```
let queueARN = '';
if (process.env.QUEUE_ARN){
    queueARN = process.env.QUEUE_ARN;
} else {
    const queue = mcClient.getQueue(queueParams).promise();
    queueARN = queue.Arn;
}
```
That way we can still enable account sharing but it also allows users to pick a queue if they want to. We can add in the functionality to provide an ARN in the advanced setup options that can also write this in the CloudFormation.

**Comment by axptwig** [comment]
the code should look something like this with the changes we made earlier to the getQueue() call.

```
  let queueARN = '';
  if (process.env.QUEUE_ARN){
    queueARN = process.env.QUEUE_ARN;
  } else {
    const q = await mcClient.getQueue(queueParams, function(err, data) {
      if (err) 
        console.log(err, err.stack); // an error occurred
      else     
        console.log(data);
      }).promise();
    queueARN = q["Queue"]["Arn"];
  }
  
  const jobParams = {
    JobTemplate: process.env.ARN_TEMPLATE,
    Queue: queueARN,
    UserMetadata: {},
    Role: process.env.MC_ROLE,
    Settings: jobSettings,
  };
```

**Pull request merged**
